version: '3.7'

services:
  cobra_app:
    image: node:13.12.0-alpine
    ports:
      - 3000:3000
    volumes:
      - ./app:/srv
    working_dir: /srv
    entrypoint: sh -c "npm install && npm start"
    tty: true