version: '3.7'

services:

  cobra_app:
    container_name: cobra_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true